#!/bin/bash

main() {
    # Array of arguments
	args=("$@")

    USERNAME=$1
    PASSWORD=$2

	# Define Destination (DEST)
	DEST='debian@192.168.8.1'
    PASS='temppwd'

    WIFI=wifi_508cb15e8a3a_656475726f616d_managed_ieee8021x
    SSID='656475726f616d'

    FILE1=[service_$WIFI
    FILE2=Type=wifi
    FILE3=SSID=$SSID
    FILE4=EAP=peap
    FILE5=Phase2=MSCHAPV2
    FILE6=Identity=$USERNAME
    FILE7=Passphrase=$PASSWORD

    WIFI_PATH='/var/lib/connman/'
    FILENAME=$WIFI.config

    #echo $FILE1] >> $WIFI_PATH/$FILENAME
    #echo $FILE2 >> $WIFI_PATH/$FILENAME
    #echo $FILE3 >> $WIFI_PATH/$FILENAME
    #echo $FILE4 >> $WIFI_PATH/$FILENAME
    #echo $FILE5 >> $WIFI_PATH/$FILENAME
    #echo $FILE6 >> $WIFI_PATH/$FILENAME
    #echo $FILE7 >> $WIFI_PATH/$FILENAME

    #scp -q /$FILENAME $DEST:$WIFI_PATH/$FILENAME
	
	sshpass -p $PASS ssh -qt $DEST "echo $PASS | sudo -S --prompt="" ls > /dev/null&&
                                    cd $WIFI_PATH &&
                                    echo '$FILE1]' | sudo tee $FILENAME > /dev/null &&
                                    echo '$FILE2' | sudo tee -a $FILENAME > /dev/null &&
                                    echo '$FILE3' | sudo tee -a $FILENAME > /dev/null &&
                                    echo '$FILE4' | sudo tee -a $FILENAME > /dev/null &&
                                    echo '$FILE5' | sudo tee -a $FILENAME > /dev/null &&
                                    echo '$FILE6' | sudo tee -a $FILENAME > /dev/null &&
                                    echo '$FILE7' | sudo tee -a $FILENAME > /dev/null &&
                                    sudo systemctl restart connman &&
                                    echo 'Connected to $WIFI'"
}

main "$@"