#!/bin/bash

main(){
	# Parse input to determine the destination IP
	if [ $# -gt 0 ] && [ $# -lt 3 ]
	then
		if [ $1 = usb ]; then
			DEST=debian@192.168.6.2

			#USB IP address is different for windows
			if [ $# -gt 1 ]; then
				if [ $2 = windows ]; then
					DEST=debian@192.168.7.2
				else
					usage_error
				fi
			fi
		elif [ $1 = wifi ]; then
			DEST=debian@192.168.8.1
		elif [ $1 = a2sys ]; then
			DEST=debian@192.168.1.101
		else
			usage_error
		fi
	else
		usage_error
	fi

	SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
	LOG_FILE=$SCRIPT_DIR/../../flight_logs/flight_logs_$(date +%F_%H%M%S)

	mkdir -p $LOG_FILE 

	rsync -avzh --progress $LOC:/home/debian/rc_pilot_logs/ $LOG_FILE 
}

usage_error(){
	echo "ERROR: Please specify beaglebone connection"
	echo "Usage: ./transfer_rcpilot [usb|wifi|a2sys] [ |windows]"
	exit 1
}

main "$@"