#!/bin/bash

main() {
	#Array of arguments
	args=("$@")

	# Define Destination (DEST)
	if [ $# -gt 1 ] && [ $# -lt 4 ]
	then
		if [ $1 = usb ]; then
			#USB IP address is different for windows
			if [ $# -gt 1 ]; then
				if [ $2 == windows ]; then
					DEST=debian@192.168.7.2
				elif [ $2 == linux ]; then
					DEST=debian@192.168.6.2
				else
					usage_error
				fi
			fi
		elif [ $1 = wifi ]; then
			DEST=debian@192.168.8.1
		elif [ $1 = a2sys ]; then
			DEST=debian@192.168.1.101
		elif [ $1 = ip ]; then
			DEST="debian@$2"
		else
			usage_error
		fi
	else
		usage_error
	fi

	echo "Transferring to $DEST"

	# Get the directory of this script
	SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
	RC_PILOT_DIR=$SCRIPT_DIR/..

	# Define the directory on the BeagleBone where 'rc_pilot_a2sys' will be transfered to
	BBB_DEST=$DEST:/home/debian/rc_pilot_a2sys/
	TMP_FILE=/tmp/include_files

	# Folders and files to transfer to the beaglebone
	INCLUDE_FILES='include/ src/ Makefile settings/'

	# Populates tmp_file with all of the files to send to the beaglebone
	# (needed by the --include-from rsync flag)
	find $INCLUDE_FILES > $TMP_FILE

	# Set the date on the beaglebone to mach source computer, eliminates clock skew on make
	if [ $# -gt 2 ] && [ ${args[2]} == timeSync ] 
	then
		DATE=$(date)
		SET_DATE="echo 'temppwd' | sudo -S date -s ""'""$DATE""'"
		ssh -t $DEST $SET_DATE
	fi

	# Transfer the files to the beaglebone.  Performs archiving operation that only updates files
	# that have newer changes on the tranfering computer.  Requires the date to be set properly for this
	# to work.
	rsync -avzh --include-from $TMP_FILE  --exclude 'docs' --exclude '.*' --exclude 'scripts' --progress $RC_PILOT_DIR $BBB_DEST
}

function usage_error() {
	echo "---------- HOW TO USE THIS SCRIPT ----------"
	echo "Usage: ./transfer_rcpilot_mac [usb|wifi|a2sys|ip] [linux|windows|<ip_address>] [ |timeSync]"
	echo ""
	echo "-----------------------------------------------------------------------"
	echo "Example 1: ./transfer_rcpilot_mac usb windows"
	echo "          will transfer files over USB if the computer is running Windows"
	echo ""
	echo "-----------------------------------------------------------------------"
	echo "Example 2: ./transfer_rcpilot_mac wifi linux"
	echo "          will transfer files over wifi if the computer is running Linux and connected to BeagleBone's Wifi."
	echo ""
	echo "Example 3: ./transfer_rcpilot_mac wifi linux timeSync"
	echo "          same as Example 2, but will set time of BeagleBone to be the same as your computer."
	echo "          DO THIS if you get 'clock skew' warnings when running MAKE"
	echo ""
	echo "-----------------------------------------------------------------------"
	echo "Example 4: ./transfer_rcpilot_mac ip <ip_address>"
	echo "          will transfer files to the device at the specified IP Address."
	echo ""
	echo "Example 5: ./transfer_rcpilot_mac ip <ip_address> timeSync"
	echo "          same as Example 4, but will set time of BeagleBone to be the same as your computer."
	echo "          DO THIS if you get 'clock skew' warnings when running MAKE"
	echo ""

	exit 1
}

main "$@"